# Generated by Django 3.1.3 on 2021-07-17 02:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tweets', '0004_tweetphoto'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='tweetphoto',
            index_together={('status', 'created_at'), ('tweet', 'order'), ('has_deleted', 'created_at'), ('user', 'created_at')},
        ),
    ]
